# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98181d06a3f81dedc3857fafe673d0a9a540163d2659a0bf1516af1dcbce62998cedf3de23a91e32c6e7fa7034aeea4ebe5a82c024c02ba0c0ef82028a98930e

test:
  secret_key_base: 7cdb6c45a82c1a8e351942cebe35788540fff3322575c14adff4cfa46ac188cef393f100c2bfb8a0a91fb219b9aa9c7fd1ba7def71578d62bd3aeb51fd903412

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
